"""create users, resume match job_postings table

Revision ID: af7e6d674876
Revises: 9ab6be68ec5a
Create Date: 2026-09-09 10:12:22.271624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af7e6d674876'
down_revision: Union[str, Sequence[str], None] = '9ab6be68ec5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('skills_score', sa.Float(), nullable=True),
    sa.Column('experience_score', sa.Float(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id')
    )
    op.create_index(op.f('ix_match_scores_id'), 'match_scores', ['id'], unique=False)
    op.add_column('job_postings', sa.Column('required_skills', sa.Text(), nullable=True))
    op.drop_column('job_postings', 'requirements')
    op.add_column('resumes', sa.Column('job_id', sa.Integer(), nullable=False))
    op.add_column('resumes', sa.Column('filename', sa.String(), nullable=False))
    op.add_column('resumes', sa.Column('parsed_data', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('resumes_job_posting_id_fkey'), 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'job_postings', ['job_id'], ['id'])
    op.drop_column('resumes', 'created_at')
    op.drop_column('resumes', 'candidate_name')
    op.drop_column('resumes', 'match_score')
    op.drop_column('resumes', 'file_path')
    op.drop_column('resumes', 'job_posting_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('job_posting_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('resumes', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('resumes', sa.Column('match_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('candidate_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.create_foreign_key(op.f('resumes_job_posting_id_fkey'), 'resumes', 'job_postings', ['job_posting_id'], ['id'])
    op.drop_column('resumes', 'uploaded_at')
    op.drop_column('resumes', 'parsed_data')
    op.drop_column('resumes', 'filename')
    op.drop_column('resumes', 'job_id')
    op.add_column('job_postings', sa.Column('requirements', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('job_postings', 'required_skills')
    op.drop_index(op.f('ix_match_scores_id'), table_name='match_scores')
    op.drop_table('match_scores')
    # ### end Alembic commands ###
